export const CART_ACTION_TYPES = {
  SET_CART_ITEMS: "cart/SET_CART_ITEMS",
  CLEAR_CART_ITEMS: "cart/CLEAR_CART_ITEMS",
  UPDATE_CART_QUANTITY: "cart/UPDATE_CART_QUANTITY",
  SET_IS_CART_COUNT: "cart/SET_IS_CART_COUNT",
  SET_IS_CART_TOTAL: "cart/SET_IS_CART_TOTAL",
};
